import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './comp/navbar/Navbar';
const inter = Inter({ subsets: ["latin"] });
import Modal from "./comp/modals/Modal";
import LoginModal from "./comp/modals/LoginModal";
import SignupModal from "./comp/modals/SignupModal";
export const metadata: Metadata = {
  title: "DjangoBNB",
  description: "Generated by Coding Hustler",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>yo</p>
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <div className="pt-32">
          {children}
        </div>
        <LoginModal/>
        <SignupModal/>
        
        {/* <Modal
          label="Modal Test"
          content={content}
          isOpen={true}
        /> */}
      </body>
    </html>
  );
}
